name: BlueWorldEditor
main: BlueWEMT\Main
version: "0.0.1"
api: [2.0.0,3.0.0]
author: "baolan"
softdepend: ["ZXDAKernel"]
commands:
 /set:
  description: Set all blocks inside the selection region to a specified block(s)
  usage: "//set <block>"
 /supersede:
  description: Replace all non-air blocks inside the selection region to a specified block(s)
  usage: "//supersede <block>"
 /fill:
  description: Replace all air blocks inside the selection region to a specified block(s)
  usage: "//fill <block>"
 /replace:
  description: Replace all blocks of the specified block with another block(s) inside the region.
  usage: "//replace <fromBlock> <toBlock>"
 /copy:
  description: Copies the currently selected region. Be aware that it stores your position relative to the selection when copying.
  usage: "//copy"
 /paste:
  description: Pastes the clipboard.
  usage: "//paste"