#单次指令最大并发数量,你内存大CPU棒可以往上加,机器渣加多可是会崩服的,小于1将视为1(暂未开放)
MaxConcurrentAtSigleCommand: 10
#自动保存的间隔，以秒为单位。好吧现在几乎没啥保存的东西，这个选项就是拿来看的
AutomaticSaveTimeInterval: 600
#所使用的界面语言,推荐保持默认,也就是Auto
LanguageUsed: Auto
#选择工具ID
SelectTool: 271
#是否只有OP才能选择区域
OnlyOPCanSelect: true
#是否只有OP才能使用本插件命令
OnlyOPCanUseCommands: true