---
#单次指令最大并发数量,你内存大CPU棒可以往上加,机器渣加多可是会崩服的,小于1将视为1
MaxConcurrentAtSigleCommand: 10
#启用异步调度,反正感觉没啥必要我就给砍了,留着这个选项你们开心就好
AsyncScheduling: false
#自动保存的间隔，以秒为单位。好吧现在几乎没啥保存的东西，这个选项就是拿来看的
AutomaticSaveTimeInterval: 600
#所使用的界面语言,推荐保持默认,也就是Auto,因为多语言就是个幌子,能用的只有中文
LanguageUsed: Auto
...
